{
    "name": "Indoor Inventario",
    "summary": "Cálculo, aprobación y aplicación mensual del costo estándar",
    "version": "18.0.6.0.0",
    "category": "Inventory/Inventory",
    "author": "Indoor",
    "license": "LGPL-3",
    "depends": ["stock_account", "purchase_stock", "sale_management", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/provisional_product_data.xml",
        "data/production_consumption_data.xml",
        "data/immobilized_product_cron.xml",
        "data/inventory_count_sequence.xml",
        "views/standard_cost_batch_views.xml",
        "views/provisional_product_views.xml",
        "views/sale_purchase_views.xml",
        "views/stock_picking_views.xml",
        "views/product_views.xml",
        "views/res_config_settings_views.xml",
        "views/product_label_layout_views.xml",
        "report/product_label_reports.xml",
        "report/product_label_templates.xml",
        "views/inventory_count_views.xml",
        "views/inventory_count_menu_views.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "indoor_inventario/static/src/scss/standard_cost_batch.scss",
            "indoor_inventario/static/src/js/protected_form_mode.js",
            "indoor_inventario/static/src/xml/protected_form_mode.xml",
            "indoor_inventario/static/src/js/barcode_auto_tab_field.js",
            "indoor_inventario/static/src/scss/inventory_count.scss",
        ],
    },
    "installable": True,
    "application": False,
}
